version: 1

formatters:
  syslog:
    format: '%(name)s: %(message)s'
  simple:
    format: '%(process)s %(asctime)s %(levelname).1s %(name)-25.25s - %(message)s'
  console:
    format: '%(message)s'

handlers:
  syslog:
    class: logging.handlers.SysLogHandler
    # handlers.syslog.address will be inferred automatically to /dev/log, /var/run/syslog or /dev/null
    # address: /dev/log
    formatter: syslog

  file:
    class: logging.handlers.WatchedFileHandler
    # handlers.file.filename will be inferred automatically to user_cache_dir/studip-log.txt
    # filename: /tmp/studip_fuse.log
    formatter: simple

  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: console

  console-err:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    formatter: console

loggers:
  studip_fuse.async_cache:
    level: INFO

  studip_fuse.cache.circuit_breaker:
    level: INFO

  studip_api.async_delay:
    level: INFO

  studip_fuse.real_path.resolve:
    level: INFO

  studip_api.Download.progress:
    level: INFO

  studip_api.model:
    level: INFO

  studip_fuse.stdout:
    handlers: [syslog, file]
    propagate: False

  studip_fuse.stderr:
    handlers: [syslog, file]
    propagate: False

  # fuse-debug prints C stderr, so print output from log-mixin to same stream
  # and don't send too long messages to syslog
  studip_fuse.fs_driver.ops:
    level: INFO
    handlers: [console-err]
    propagate: False

root:
  level: DEBUG
  handlers: [syslog, file, console]

disable_existing_loggers: False
