version: 1

formatters:
  syslog:
    format: '%(name)s: %(message)s'
  simple:
    format: '%(process)s %(asctime)s %(levelname).1s %(name)-25.25s - %(message)s'
  console:
    format: '%(message)s'

handlers:
  syslog:
    class: logging.handlers.SysLogHandler
    # handlers.syslog.address will be inferred automatically to /dev/log, /var/run/syslog or /dev/null
    # address: /dev/log
    formatter: syslog

  file:
    class: logging.handlers.WatchedFileHandler
    # handlers.file.filename will be inferred automatically to user_data_dir/studip-log.txt
    # filename: /tmp/studip_fuse.log
    formatter: simple

  status:
    class: logging.handlers.WatchedFileHandler
    # handlers.file.filename will be inferred automatically to user_data_dir/studip-status.txt
    # filename: /tmp/studip_fuse_status.log
    formatter: console

  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: console

  console-err:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    formatter: console

loggers:
  studip_fuse.status:
    level: DEBUG
    handlers: [status]
    propagate: False

  studip_fuse.stdout:
    handlers: [syslog, file]
    propagate: False

  studip_fuse.stderr:
    handlers: [syslog, file]
    propagate: False

  aiohttp.access:
    level: WARN

root:
  level: DEBUG
  handlers: [syslog, file, console]

disable_existing_loggers: False
